# Desde la terminal descargo el paquete/librerÃ­a de conexion con la siguiente sentecia:
# pip install mysql-connector-python

import mysql.connector
# importarmos el conector

# Iniciamos un try
try:
    #creamos la variable conexion de mysql
    conn = mysql.connector.connect(user='root', password='', host='localhost', database='', port='')
    
    #print(conexion)
    # al digitar en la consola >python conexion.py me debe de salir un msj similar a "Connection objet at..."

except Exception as err:
    print('ERROR al conectar a la base de datos')

else:
    print('CONEXION A LA BDD SATISFACTORIA')

#cerramos la conexion
conn.close()
